// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package db

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (date, exercise_type, duration)
VALUES (?, ?, ?)
RETURNING id, date, exercise_type, duration, created_at
`

type CreateExerciseParams struct {
	Date         string `json:"date"`
	ExerciseType string `json:"exercise_type"`
	Duration     int64  `json:"duration"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise, arg.Date, arg.ExerciseType, arg.Duration)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.ExerciseType,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercises
WHERE id = ?
`

func (q *Queries) DeleteExercise(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExercise, id)
	return err
}

const listExercises = `-- name: ListExercises :many
SELECT id, date, exercise_type, duration, created_at FROM exercises
ORDER BY date DESC
LIMIT ?
`

func (q *Queries) ListExercises(ctx context.Context, limit int64) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercises, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.ExerciseType,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesByDate = `-- name: ListExercisesByDate :many
SELECT id, date, exercise_type, duration, created_at FROM exercises
WHERE date = ?
ORDER BY created_at
`

func (q *Queries) ListExercisesByDate(ctx context.Context, date string) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercisesByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.ExerciseType,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesFromDate = `-- name: ListExercisesFromDate :many
SELECT id, date, exercise_type, duration, created_at FROM exercises
WHERE date >= ?
ORDER BY date ASC
`

func (q *Queries) ListExercisesFromDate(ctx context.Context, date string) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercisesFromDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.ExerciseType,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
