// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package db

import (
	"context"
)

const createMeal = `-- name: CreateMeal :one

INSERT INTO meals (name, protein, carbs, fat, calories)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, protein, carbs, fat, calories, created_at, last_logged
`

type CreateMealParams struct {
	Name     string `json:"name"`
	Protein  int64  `json:"protein"`
	Carbs    int64  `json:"carbs"`
	Fat      int64  `json:"fat"`
	Calories int64  `json:"calories"`
}

// Meal Templates (saved meals)
func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, createMeal,
		arg.Name,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Calories,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Calories,
		&i.CreatedAt,
		&i.LastLogged,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals
WHERE id = ?
`

func (q *Queries) DeleteMeal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMeal, id)
	return err
}

const deleteMealLog = `-- name: DeleteMealLog :exec
DELETE FROM meal_logs
WHERE id = ?
`

func (q *Queries) DeleteMealLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMealLog, id)
	return err
}

const getDailyTotals = `-- name: GetDailyTotals :one
SELECT 
  COALESCE(SUM(protein), 0) as total_protein,
  COALESCE(SUM(carbs), 0) as total_carbs,
  COALESCE(SUM(fat), 0) as total_fat,
  COALESCE(SUM(calories), 0) as total_calories
FROM meal_logs
WHERE date = ?
`

type GetDailyTotalsRow struct {
	TotalProtein  interface{} `json:"total_protein"`
	TotalCarbs    interface{} `json:"total_carbs"`
	TotalFat      interface{} `json:"total_fat"`
	TotalCalories interface{} `json:"total_calories"`
}

func (q *Queries) GetDailyTotals(ctx context.Context, date string) (GetDailyTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getDailyTotals, date)
	var i GetDailyTotalsRow
	err := row.Scan(
		&i.TotalProtein,
		&i.TotalCarbs,
		&i.TotalFat,
		&i.TotalCalories,
	)
	return i, err
}

const getMealByName = `-- name: GetMealByName :one
SELECT id, name, protein, carbs, fat, calories, created_at, last_logged FROM meals
WHERE name = ?
`

func (q *Queries) GetMealByName(ctx context.Context, name string) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMealByName, name)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Calories,
		&i.CreatedAt,
		&i.LastLogged,
	)
	return i, err
}

const listDailyCaloriesFromDate = `-- name: ListDailyCaloriesFromDate :many
SELECT
  date,
  COALESCE(SUM(calories), 0) as total_calories
FROM meal_logs
WHERE date >= ?
GROUP BY date
ORDER BY date ASC
`

type ListDailyCaloriesFromDateRow struct {
	Date          string      `json:"date"`
	TotalCalories interface{} `json:"total_calories"`
}

func (q *Queries) ListDailyCaloriesFromDate(ctx context.Context, date string) ([]ListDailyCaloriesFromDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyCaloriesFromDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyCaloriesFromDateRow
	for rows.Next() {
		var i ListDailyCaloriesFromDateRow
		if err := rows.Scan(&i.Date, &i.TotalCalories); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealLogsByDate = `-- name: ListMealLogsByDate :many
SELECT 
  ml.id,
  ml.date,
  ml.created_at,
  ml.protein,
  ml.carbs,
  ml.fat,
  ml.calories,
  m.name
FROM meal_logs ml
JOIN meals m ON m.id = ml.meal_id
WHERE ml.date = ?
ORDER BY ml.created_at
`

type ListMealLogsByDateRow struct {
	ID        int64  `json:"id"`
	Date      string `json:"date"`
	CreatedAt string `json:"created_at"`
	Protein   int64  `json:"protein"`
	Carbs     int64  `json:"carbs"`
	Fat       int64  `json:"fat"`
	Calories  int64  `json:"calories"`
	Name      string `json:"name"`
}

func (q *Queries) ListMealLogsByDate(ctx context.Context, date string) ([]ListMealLogsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listMealLogsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealLogsByDateRow
	for rows.Next() {
		var i ListMealLogsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.CreatedAt,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.Calories,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeals = `-- name: ListMeals :many
SELECT id, name, protein, carbs, fat, calories, created_at, last_logged FROM meals
ORDER BY last_logged DESC, created_at DESC, name
LIMIT ?
`

func (q *Queries) ListMeals(ctx context.Context, limit int64) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listMeals, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.Calories,
			&i.CreatedAt,
			&i.LastLogged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logMeal = `-- name: LogMeal :one

INSERT INTO meal_logs (meal_id, protein, carbs, fat, calories, date)
SELECT id, protein, carbs, fat, calories, ? 
FROM meals 
WHERE name = ?
RETURNING id, meal_id, date, created_at, protein, carbs, fat, calories
`

type LogMealParams struct {
	Date string `json:"date"`
	Name string `json:"name"`
}

// Meal Logs (daily tracking)
// Log meal with saved portions (copies from meals table)
func (q *Queries) LogMeal(ctx context.Context, arg LogMealParams) (MealLog, error) {
	row := q.db.QueryRowContext(ctx, logMeal, arg.Date, arg.Name)
	var i MealLog
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.Date,
		&i.CreatedAt,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Calories,
	)
	return i, err
}

const logMealWithPortions = `-- name: LogMealWithPortions :one
INSERT INTO meal_logs (meal_id, protein, carbs, fat, calories, date)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, meal_id, date, created_at, protein, carbs, fat, calories
`

type LogMealWithPortionsParams struct {
	MealID   int64  `json:"meal_id"`
	Protein  int64  `json:"protein"`
	Carbs    int64  `json:"carbs"`
	Fat      int64  `json:"fat"`
	Calories int64  `json:"calories"`
	Date     string `json:"date"`
}

func (q *Queries) LogMealWithPortions(ctx context.Context, arg LogMealWithPortionsParams) (MealLog, error) {
	row := q.db.QueryRowContext(ctx, logMealWithPortions,
		arg.MealID,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Calories,
		arg.Date,
	)
	var i MealLog
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.Date,
		&i.CreatedAt,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Calories,
	)
	return i, err
}

const updateMeal = `-- name: UpdateMeal :exec
UPDATE meals
SET protein = ?, carbs = ?, fat = ?, calories = ?
WHERE name = ?
`

type UpdateMealParams struct {
	Protein  int64  `json:"protein"`
	Carbs    int64  `json:"carbs"`
	Fat      int64  `json:"fat"`
	Calories int64  `json:"calories"`
	Name     string `json:"name"`
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) error {
	_, err := q.db.ExecContext(ctx, updateMeal,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Calories,
		arg.Name,
	)
	return err
}

const updateMealLastLogged = `-- name: UpdateMealLastLogged :exec
UPDATE meals
SET last_logged = ?
WHERE name = ?
`

type UpdateMealLastLoggedParams struct {
	LastLogged string `json:"last_logged"`
	Name       string `json:"name"`
}

func (q *Queries) UpdateMealLastLogged(ctx context.Context, arg UpdateMealLastLoggedParams) error {
	_, err := q.db.ExecContext(ctx, updateMealLastLogged, arg.LastLogged, arg.Name)
	return err
}
