// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package db

import (
	"context"
	"database/sql"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (date, name, protein, carbs, fat, calories)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, date, name, protein, carbs, fat, calories, created_at
`

type CreateMealParams struct {
	Date     string `json:"date"`
	Name     string `json:"name"`
	Protein  int64  `json:"protein"`
	Carbs    int64  `json:"carbs"`
	Fat      int64  `json:"fat"`
	Calories int64  `json:"calories"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, createMeal,
		arg.Date,
		arg.Name,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Calories,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Name,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Calories,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyTotals = `-- name: GetDailyTotals :one
SELECT 
  SUM(protein) as total_protein,
  SUM(carbs) as total_carbs,
  SUM(fat) as total_fat,
  SUM(calories) as total_calories
FROM meals
WHERE date = ?
`

type GetDailyTotalsRow struct {
	TotalProtein  sql.NullFloat64 `json:"total_protein"`
	TotalCarbs    sql.NullFloat64 `json:"total_carbs"`
	TotalFat      sql.NullFloat64 `json:"total_fat"`
	TotalCalories sql.NullFloat64 `json:"total_calories"`
}

func (q *Queries) GetDailyTotals(ctx context.Context, date string) (GetDailyTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getDailyTotals, date)
	var i GetDailyTotalsRow
	err := row.Scan(
		&i.TotalProtein,
		&i.TotalCarbs,
		&i.TotalFat,
		&i.TotalCalories,
	)
	return i, err
}

const listMealsByDate = `-- name: ListMealsByDate :many
SELECT id, date, name, protein, carbs, fat, calories, created_at FROM meals
WHERE date = ?
ORDER BY created_at
`

func (q *Queries) ListMealsByDate(ctx context.Context, date string) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listMealsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Name,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.Calories,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
