// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Exercise struct {
	ID           int64  `json:"id"`
	Date         string `json:"date"`
	ExerciseType string `json:"exercise_type"`
	Duration     int64  `json:"duration"`
	CreatedAt    string `json:"created_at"`
}

type Meal struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Protein    int64  `json:"protein"`
	Carbs      int64  `json:"carbs"`
	Fat        int64  `json:"fat"`
	Calories   int64  `json:"calories"`
	CreatedAt  string `json:"created_at"`
	LastLogged string `json:"last_logged"`
}

type MealLog struct {
	ID        int64  `json:"id"`
	MealID    int64  `json:"meal_id"`
	Date      string `json:"date"`
	CreatedAt string `json:"created_at"`
	Protein   int64  `json:"protein"`
	Carbs     int64  `json:"carbs"`
	Fat       int64  `json:"fat"`
	Calories  int64  `json:"calories"`
}

type Weight struct {
	ID        int64  `json:"id"`
	Date      string `json:"date"`
	Pounds    int64  `json:"pounds"`
	CreatedAt string `json:"created_at"`
}
