// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weights.sql

package db

import (
	"context"
)

const createWeight = `-- name: CreateWeight :one
INSERT INTO weights (date, pounds)
VALUES (?, ?)
RETURNING id, date, pounds, created_at
`

type CreateWeightParams struct {
	Date   string `json:"date"`
	Pounds int64  `json:"pounds"`
}

func (q *Queries) CreateWeight(ctx context.Context, arg CreateWeightParams) (Weight, error) {
	row := q.db.QueryRowContext(ctx, createWeight, arg.Date, arg.Pounds)
	var i Weight
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Pounds,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWeight = `-- name: DeleteWeight :exec
DELETE FROM weights
WHERE id = ?
`

func (q *Queries) DeleteWeight(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWeight, id)
	return err
}

const getWeightByDate = `-- name: GetWeightByDate :one
SELECT id, date, pounds, created_at FROM weights
WHERE date = ?
`

func (q *Queries) GetWeightByDate(ctx context.Context, date string) (Weight, error) {
	row := q.db.QueryRowContext(ctx, getWeightByDate, date)
	var i Weight
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Pounds,
		&i.CreatedAt,
	)
	return i, err
}

const listWeights = `-- name: ListWeights :many
SELECT id, date, pounds, created_at FROM weights
ORDER BY date DESC
LIMIT ?
`

func (q *Queries) ListWeights(ctx context.Context, limit int64) ([]Weight, error) {
	rows, err := q.db.QueryContext(ctx, listWeights, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weight
	for rows.Next() {
		var i Weight
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Pounds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeightsFromDate = `-- name: ListWeightsFromDate :many
SELECT id, date, pounds, created_at FROM weights
WHERE date >= ?
ORDER BY date ASC
`

func (q *Queries) ListWeightsFromDate(ctx context.Context, date string) ([]Weight, error) {
	rows, err := q.db.QueryContext(ctx, listWeightsFromDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weight
	for rows.Next() {
		var i Weight
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Pounds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWeight = `-- name: UpdateWeight :exec
UPDATE weights
SET pounds = ?
WHERE date = ?
`

type UpdateWeightParams struct {
	Pounds int64  `json:"pounds"`
	Date   string `json:"date"`
}

func (q *Queries) UpdateWeight(ctx context.Context, arg UpdateWeightParams) error {
	_, err := q.db.ExecContext(ctx, updateWeight, arg.Pounds, arg.Date)
	return err
}
